/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Control.Exceptions.NaoEncontradoException;
import DAO.CaixaDAO;
import Modelo.CaixaModel;
import Modelo.FuncionarioModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author pedro
 */
public class PrincipalFuncionarioView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFuncionarioView
     */
    FuncionarioModel funcionarioModel;
    PrincipalGerenteView gv;
    
    public PrincipalFuncionarioView(FuncionarioModel funcionarioModel,PrincipalGerenteView gv) {
        initComponents();
        this.gv = gv;
        Timer timer = new Timer(1000, new PrincipalFuncionarioView.hora());
        timer.start();
        funcionarioModel = funcionarioModel;
        jLabelLegendaNome.setText(funcionarioModel.getNome());
       
        try{
            CaixaDAO caixaDao = new CaixaDAO();
            CaixaModel caixaModel = new CaixaModel();
            caixaModel = caixaDao.pesquisarCaixa();

            mudaTexto(caixaModel);
          
            }catch(NaoEncontradoException e){
                System.err.println(e);
                jLabelStatusCaixa.setText("caixa nao encontrado");
            } catch (SQLException ex) {
            Logger.getLogger(PrincipalFuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
    }
    
//     public void mudaTexto(CaixaModel caixaModel) throws SQLException, NaoEncontradoException{
//        
//        jLabelStatusCaixa.setText(caixaModel.getSituacao());
//        
//        if(caixaModel.getSituacao().equals("aberto")){
//        String data = new SimpleDateFormat("dd/MM/yyyy").format(caixaModel.getDataAbertura());
//        jLabelDataAbertura.setText(data);
//        jLabelLegendaDataAberturaFechamento.setText("Data Abertura:");
//        }else{
//        String data = new SimpleDateFormat("dd/MM/yyyy").format(caixaModel.getDataFechamento());    
//        jLabelDataAbertura.setText(data);
//        jLabelLegendaDataAberturaFechamento.setText("Data Fechamento");
//        } 
//        
//    }
    public void mudaTexto(CaixaModel caixaModel) throws SQLException, NaoEncontradoException{
        
        jLabelStatusCaixa.setText(caixaModel.getSituacao());
        
        if(caixaModel.getSituacao().equals("aberto")){
            String data = new SimpleDateFormat("dd/MM/yyyy").format(caixaModel.getDataAbertura());
            jLabelDataAbertura.setText(data);
            jLabelLegendaDataAberturaFechamento.setText("Data Abertura:");
            
        }else{
            String data = new SimpleDateFormat("dd/MM/yyyy").format(caixaModel.getDataFechamento());    
            jLabelDataAbertura.setText(data);
            jLabelLegendaDataAberturaFechamento.setText("Data Fechamento");
            
            jLabelDataAbertura.addMouseListener(new MouseAdapter() { 
                    
                public void mouseClicked(MouseEvent evt) 
                        { 
                            if (evt.getClickCount() == 2){
                                 
                            } 
                        }
                });
        } 
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonCaixa = new javax.swing.JButton();
        jButtonProduto = new javax.swing.JButton();
        jButtonCliente = new javax.swing.JButton();
        jButtonEstoque = new javax.swing.JButton();
        jButtonVenda = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLegendaDataAberturaFechamento = new javax.swing.JLabel();
        jLabelLegendaNome = new javax.swing.JLabel();
        jLabelStatusCaixa = new javax.swing.JLabel();
        jLabelDataAbertura = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelRelogio = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSairLogin = new javax.swing.JMenuItem();
        jMenuItemSairSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setExtendedState(6);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButtonCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Caixa80x80.png"))); // NOI18N
        jButtonCaixa.setText("Caixa");
        jButtonCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaixaActionPerformed(evt);
            }
        });

        jButtonProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Produtos70x70.png"))); // NOI18N
        jButtonProduto.setText("Produtos");
        jButtonProduto.setActionCommand("Caixa");
        jButtonProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoActionPerformed(evt);
            }
        });

        jButtonCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cliente80x80.png"))); // NOI18N
        jButtonCliente.setText("Cliente");
        jButtonCliente.setActionCommand("Caixa");
        jButtonCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });

        jButtonEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/carrinhoCaixa80x80.png"))); // NOI18N
        jButtonEstoque.setText("Estoque");
        jButtonEstoque.setActionCommand("Caixa");
        jButtonEstoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEstoque.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonEstoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstoqueActionPerformed(evt);
            }
        });

        jButtonVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Venda70x70.png"))); // NOI18N
        jButtonVenda.setText("Venda");
        jButtonVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVenda.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/imagensConfig/logoCasaTempero.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(10, 177, 209));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 100));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Caixa:");

        jLabelLegendaDataAberturaFechamento.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabelLegendaDataAberturaFechamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLegendaDataAberturaFechamento.setText("Data Abertura:");

        jLabelLegendaNome.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabelLegendaNome.setForeground(new java.awt.Color(255, 255, 255));

        jLabelStatusCaixa.setBackground(new java.awt.Color(255, 255, 255));
        jLabelStatusCaixa.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabelStatusCaixa.setForeground(new java.awt.Color(255, 255, 255));

        jLabelDataAbertura.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDataAbertura.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabelDataAbertura.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Relógio");

        jLabelRelogio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRelogio.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabelRelogio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRelogio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel5.setBackground(new java.awt.Color(10, 177, 209));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLegendaNome, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatusCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLegendaDataAberturaFechamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRelogio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRelogio, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDataAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelStatusCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLegendaNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelLegendaDataAberturaFechamento)
                                .addComponent(jLabel1)))))
                .addContainerGap())
        );

        jMenu1.setText("Controle");

        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCliente);

        jMenuItemProduto.setText("Produto");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemProduto);

        jMenuBar1.add(jMenu1);

        jMenuSair.setText("Sair");

        jMenuItemSairLogin.setText("Sair para Login");
        jMenuItemSairLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairLoginActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSairLogin);

        jMenuItemSairSistema.setText("Sair do Sistema");
        jMenuItemSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairSistemaActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSairSistema);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        try {
            ManterClienteView manterCliente = new ManterClienteView(null,true, "principal");
            manterCliente.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NaoEncontradoException ex) {
            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
//        try {
//            ManterProdutoView manterProduto = new ManterProdutoView(null,true){};
//            manterProduto.setVisible(true);
//        } catch (ParseException ex) {
//            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jMenuItemSairLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairLoginActionPerformed
        LoginView login = new LoginView(null,true);
        dispose();
        login.setVisible(true);

    }//GEN-LAST:event_jMenuItemSairLoginActionPerformed

    private void jMenuItemSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairSistemaActionPerformed

    private void jButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoActionPerformed
        try {
            ManterProdutoView manterProduto = new ManterProdutoView(null,true,"");
            manterProduto.setVisible(true);
           
        } catch (ParseException ex) {
            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonProdutoActionPerformed

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        try {
            ManterClienteView manterCliente = new ManterClienteView(null,true,"principal");
            manterCliente.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NaoEncontradoException ex) {
            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButtonCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaixaActionPerformed
        ControleCaixaView caixa = new ControleCaixaView(this.funcionarioModel, this.gv, this);
        caixa.setVisible(true);
        
    }//GEN-LAST:event_jButtonCaixaActionPerformed

    private void jButtonEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstoqueActionPerformed

        ControleEstoqueView estoque = null;

        estoque = new ControleEstoqueView(null);

        estoque.setVisible(true);
    }//GEN-LAST:event_jButtonEstoqueActionPerformed

    private void jButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaActionPerformed

        CaixaModel caixaModel = new CaixaModel();
        CaixaDAO caixaDao = new CaixaDAO();

        try {
            caixaModel = caixaDao.pesquisarCaixa();

            if("fechado".equals(caixaModel.getSituacao())){

                JOptionPane.showMessageDialog(null, "Faça a abertura do caixa para continuar", "Alerta, O caixa não está aberto!",JOptionPane.WARNING_MESSAGE);

                ControleCaixaView caixa = null;

                caixa = new ControleCaixaView(this.funcionarioModel, this.gv, this);
                caixa.setVisible(true);

            }else{

                if(caixaModel.getFinaliza() == false){

                    Venda venda = new Venda("", null, null, this.gv);
                    venda.setVisible(true);

                }else{
                    String data = new SimpleDateFormat("dd/MM/yyyy").format(caixaModel.getDataAbertura());
                    JOptionPane.showMessageDialog(null, "O caixa do dia "+data+" esta com diferença de valores. Verificar problema ?","alerta",JOptionPane.WARNING_MESSAGE);

                    ControleCaixaView caixa = null;

                    caixa = new ControleCaixaView(this.funcionarioModel, this.gv, this);
                    caixa.setVisible(true);

                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NaoEncontradoException ex) {
            Logger.getLogger(PrincipalGerenteView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFuncionarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFuncionarioView(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCaixa;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonEstoque;
    private javax.swing.JButton jButtonProduto;
    private javax.swing.JButton jButtonVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDataAbertura;
    private javax.swing.JLabel jLabelLegendaDataAberturaFechamento;
    private javax.swing.JLabel jLabelLegendaNome;
    private javax.swing.JLabel jLabelRelogio;
    private javax.swing.JLabel jLabelStatusCaixa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemSairLogin;
    private javax.swing.JMenuItem jMenuItemSairSistema;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
    class hora implements ActionListener{
    @Override
    public void actionPerformed(ActionEvent e){
        
    Calendar now = Calendar.getInstance();
        jLabelRelogio.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        
     }
    }

}
